print("\t\t\t   \"Trees\"")
print("\t\t    I think that I shall")
print("\t      never see. A poem lovely as a tree.")
print("\t      A tree whose hungry mouth is prest.")
print("\t   Against the earth’s sweet flowing breast;")
print("\tA tree that looks at God all day, And lifts her") 
print("\t    leafy arms to pray; A tree that may in")
print("\t   Summer wear. A nest of robins in her hair;")
print("\t        Upon whose bosom snow has lain;")
print("\t        Who intimately lives with rain.")
print("\t\t\t    Poems")
print("\t\t\t     are")
print("\t\t\t     made")
print("\t\t\t      by")
print("\t\t\t    fools like me.")
print("\t\t\t     But")
print("\t\t\t     only")
print("\t\t\t     God")
print("\t\t\t     can")
print("\t\t\t make a tree.") 